set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set number
set cursorline
set nowrap
set sidescroll=
set smartindent
set smarttab

" Auto ([{
inoremap ' ''<ESC>i
inoremap " ""<ESC>i
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i

" yaml file settting
filetype on
autocmd Filetype yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Normal ❚ Insert |
if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[2 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[4 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif
