set nocompatible                  " use vim defaults
set showcmd                       " display incomplete commands
set showmatch                     " jump to matchs when entering parenthes
set matchtime=1                   " tenths of a secend to show the matching parenthes
set backspace=indent,eol,start    " make that backspace key work the way it should
set textwidth=0                   " don't wrap lines by default
set ruler                         " show the current row and column
set number                        " show line numbers

set nowrap                        " line exceed screen don't wrap
set sidescroll=1                  " line exceed screen cursor smooth scrolling
set cursorline                    " highlight cursorline

set novisualbell                  " turn off visualbell
set noerrorbells                  " turn off errorbell

set hlsearch                      " highlight searchs
set incsearch                     " do incremental searching
set ignorecase                    " ignore case when searching
set smartcase                     " no ignorecase if Uppercase char present

set autoindent                    " always set autoindenting on
set smartindent                   " indent works for c-like
set tabstop=4                     " <Tab> width look for
set expandtab                     " expand <Tab> as spaces
set softtabstop=4                 " spaces number when insert <Tab>
set shiftround                    " indent not to multiple of 'shiftwidth'
set shiftwidth=4                  " number of spaces to use for (auto)indent

if &term == "xterm"
    if has("terminfo")
        set t_Co=8
        set t_Sf=^[[3%p1%dm
        set t_Sb=^[[4%p1%dm
    else
        set t_Co=8
        set t_Sf=^[[3%dm
        set t_Sb=^[[4%dm
    endif
endif

syntax on                         " turn syntax highlighting on by default

" Specify file config
filetype plugin indent on
autocmd Filetype yaml set tabstop=2 shiftwidth=2 softtabstop=2

" Theme
" set t_Co=256
set termguicolors
colorscheme yowish
hi Normal guibg=NONE ctermbg=none
hi CursorLine guibg=#31353F
hi LineNr guifg=#949494 ctermfg=246
" hi Comment ctermfg=241
