set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set number
set cursorline
set nowrap
set sidescroll=1
set smartindent
set smarttab
set laststatus=2

" Auto ([{
inoremap ' ''<ESC>i
inoremap " ""<ESC>i
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {<CR>}<ESC>O

" yaml file settting
filetype on
autocmd Filetype yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Gnome3 Normal ❚ Insert |
if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[2 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[4 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif

" Windows Terminal wsl2 Normal ❚ Insert |
if &term =~ "xterm"
    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[3 q"
    let &t_EI = "\<Esc>[2 q"
endif
